name: IridiumSkyblock
version: 2.4.1
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: IridiumLLC
load: STARTUP
depend: [Vault]
softdepend: [WorldEdit, PlaceholderAPI, MVdWPlaceholderAPI, WildStacker, EpicSpawners, UltimateStacker, MergedSpawner, Vault, Multiverse-Core, Essentials, EssentialsChat, ChatManager, DeluxeChat]
commands:
  area:
    description: Main plugin command